---
# tasks file for mysql
- name: install tools
  apt: name={{item}} state=present
  with_items:
    - python-mysqldb

- name: install mysql-server
  apt: name=mysql-server state=present

- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
              line="bind-address = {{ ansible_eth0.ipv4.address }}"
  notify: restart mysql

- name: ensure mysql is started
  service: name=mysql state=started enabled=yes

- name: create {{ db_name }} database
  mysql_db: name={{ db_name }} state=present

- name: create {{ db_user_name }} user
  # all privileges for user demo on database demo, can be accessed from anywhere
  # see DATABASE_URI in demo.wsgi
  mysql_user: name={{ db_user_name }} password={{ db_user_password }}
              priv={{ db_name }}.*:ALL host='{{ db_user_host }}' state=present
