---
# tasks file for mysql
- name: install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - python-mysqldb

- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
              line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: ensure mysql is started
  service: name=mysql state=started enabled=yes

- name: create demo database
  mysql_db: name=demo state=present

- name: create demo user
  # all privileges for user demo on database demo, can be accessed from anywhere
  # see DATABASE_URI in demo.wsgi
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present
